# Application configuration
rpc:
  listen: tcp://127.0.0.1:6001

app:
  command: "php app/app.php"
  env:
    DEBUG: true

# Workflow and activity mesh service
temporal:
  address: "localhost:7233"
  activities:
    numWorkers: 1